#!/usr/bin/env python

Import("env")

import platform_nx_builders

common_nx = [
    "os_nx.cpp",
    "display_server_nx.cpp",
    "audio_driver_nx.cpp",
    "joypad_nx.cpp",
    "file_access_nx.cpp",
    "dir_access_nx.cpp",
    "netsocket_nx.cpp",
    "ip_nx.cpp",
]

if env["opengl3"]:
    common_nx.append("gl_manager_nx.cpp")

if env["vulkan"]:
    common_nx.append("vulkan_context_nx.cpp")

env.Depends("#platform/nx/applet_splash.gen.h", "#platform/nx/applet_splash.rgba.gz")
env.CommandNoCache(
    "#platform/nx/applet_splash.gen.h",
    "#platform/nx/applet_splash.rgba.gz",
    env.Run(platform_nx_builders.make_applet_splash, "Building applet splash header."),
)

prog = env.add_program("#bin/godot", ["godot_nx.cpp"] + common_nx)
